# Generated by Django 3.1.7 on 2021-05-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
