# Generated by Django 3.1.7 on 2021-05-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0004_auto_20210530_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_denied',
            new_name='Approved',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='is_pending',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_passed',
        ),
    ]
