# Generated by Django 3.2.3 on 2021-05-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0005_auto_20210530_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
