# Generated by Django 3.2.3 on 2021-05-30 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0006_alter_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userss.profile'),
        ),
    ]
